### PR TITLE
Update PasswordValidation.py and Fixing Security.py

### PR DESCRIPTION
**Pull request by PsychoRover**
Added a regex solution.

### CODE REVIEW

**Comment by rabestro** [comment]
Hi,

Thank you for a tricky regex! 
I need time to understand it :)

**Comment by PsychoRover** [comment]
> Hi,
> 
> Thank you for a tricky regex!
> I need time to understand it :)

A sucker for one liners!
It really does the job well!

**Comment by PsychoRover** [comment]
I fixed your 'Security.py' code!
Have fun testing it!

**Review by rabestro — APPROVED** [review]
Nice solutions!

**Comment by rabestro** [comment]
Thank you!

**Pull request merged**
